version: '2.1'

services:
    mysql:
        image: "percona:latest"
        container_name: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: test
            MYSQL_USER: test_qa
            MYSQL_PASSWORD: qa_test
        volumes:
            - ./database:/docker-entrypoint-initdb.d

        healthcheck:
            test: ['CMD', 'mysqladmin', '-uroot', '-ppass', 'ping', '-h', '127.0.0.1']
            timeout: 1s
            retries: 30
    
    vk_api:
        image: "vk_api:latest"
        container_name: vk_api
        ports:
            - 8083:8083

    myapp:
        image: "myapp:latest"
        container_name: myapp
        ports:
            - 7080:7080
        volumes:
            - ./app:/tmp
        depends_on:
            mysql:
                condition: service_healthy

        entrypoint: /bin/bash /tmp/start_app.sh

networks:
    default:
        external: true
        name: myapp-net